Casmcms 8824
Cray-HPE/csm-config pull request #247
Opened 2024-02-26 14:56 UTC by juliansmit-hpe

## Summary and Scope

Modified the ims remote play to configure an arm based compute.

## Issues and Related PRs

https://jira-pro.it.hpe.com:8443/browse/CASMCMS-8824

## Testing

### Tested on:
Mug/Baldar/Tyr

### Test description:

Tested play execution against bare metal image from the metal team as well as an IMS built barebones image.
## Risks and Mitigations

No

## Pull Request Checklist

- [x] Version number(s) incremented, if applicable
- [x] Copyrights updated
- [x] License file intact
- [x] Target branch correct
- [x] CHANGELOG.md updated
- [x] Testing is appropriate and complete, if applicable
- [x] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable

2024-02-27 17:34 UTC, mharding-hpe requested changes
Also need to update the CHANGELOG

2024-02-27 17:34 UTC, mharding-hpe commented on ansible/ims_computes.yml
Copyright header in this file needs to be updated to include the current year

2024-02-27 17:34 UTC, mharding-hpe commented on ansible/roles/csm.ims-remote/defaults/main.yml
Copyright header in this file needs to be updated to include the current year

2024-02-27 17:34 UTC, mharding-hpe commented on ansible/roles/csm.ims-remote/tasks/main.yml
Copyright header in this file needs to be updated to include the current year

2024-02-27 17:34 UTC, mharding-hpe commented on ansible/vars/csm_ims_repos.yml
Copyright header in this file needs to be updated to include the current year

2024-02-27 17:34 UTC, mharding-hpe commented on ansible/vars/csm_ims_repos.yml
> +- name: SUSE-SLE-Module-Basesystem-15-SP5-aarch64-Pool
```suggestion
- name: SUSE-SLE-Module-Containers-${releasever_major}-SP${releasever_minor}-aarch64-Pool
  description: "Suse container modules (added by Ansible)"
  repo: https://packages.local/repository/SUSE-SLE-Module-Containers-${releasever_major}-SP${releasever_minor}-aarch64-Pool
- name: SUSE-SLE-Module-Basesystem-${releasever_major}-SP${releasever_minor}-aarch64-Pool
```

2024-02-27 17:34 UTC, mharding-hpe commented on ansible/vars/csm_ims_repos.yml
> +  repo: https://packages.local/repository/SUSE-SLE-Module-Basesystem-15-SP5-aarch64-Pool
```suggestion
  repo: https://packages.local/repository/SUSE-SLE-Module-Basesystem-${releasever_major}-SP${releasever_minor}-aarch64-Pool
```

2024-02-27 17:35 UTC, mharding-hpe commented on ansible/vars/csm_ims_repos.yml
Is it intended to remove the x86 repos entirely (rather than just add the aarch64 ones)? Is the IMS remote play only ever going to be executed on aarch64 targets?

2024-02-28 15:57 UTC, mharding-hpe commented
I'll add a commit to cover the copyright nitpicks in my comments.

2024-03-04 22:07 UTC, juliansmit-hpe commented on ansible/vars/csm_ims_repos.yml
We can utilize both architectures if we choose to do so. I've re-added the repos in question.

2024-03-05 17:59 UTC, mharding-hpe approved these changes

2024-03-05 18:09 UTC, dlaine-hpe approved these changes

2024-03-05 18:11 UTC, merged

2024-03-05 18:26 UTC, jsl-hpe approved these changes