CASMPET-6980: Enable/ start SBPS marshal agent systemd service during…
Cray-HPE/csm-config pull request #269
Opened 2024-05-21 15:31 UTC by ravikanth-nalla-hpe

… worker node personalization

    - Start SBPS marshal agent systemd service (post install) during
      node personalizaion.

## Summary and Scope

_Summarize what has changed. Explain why this PR is necessary. What is impacted? Is this a new feature, critical bug fix, etc?_

_Is this change backwards incompatible, backwards compatible, or a backwards compatible bugfix?_

## Issues and Related PRs

_List and characterize relationship to Jira/Github issues and other pull requests. Be sure to list dependencies._

* Resolves [issue id](issue link)
* Change will also be needed in `<insert branch name here>`
* Future work required by [issue id](issue link)
* Documentation changes required in [issue id](issue link)
* Merge with/before/after `<insert PR URL here>`

## Testing

_List the environments in which these changes were tested._

### Tested on:

  * `<development system>`
  * Local development environment
  * Virtual Shasta

### Test description:

_How were the changes tested and success verified? If schema changes were part of this change, how were those handled in your upgrade/downgrade testing?_

- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)?
- Were continuous integration tests run? If not, why?
- Was upgrade tested? If not, why?
- Was downgrade tested? If not, why?
- Were new tests (or test issues/Jiras) created for this change?

## Risks and Mitigations

_Are there known issues with these changes? Any other special considerations?_

## Pull Request Checklist

- [ ] Version number(s) incremented, if applicable
- [ ] Copyrights updated
- [ ] License file intact
- [ ] Target branch correct
- [ ] CHANGELOG.md updated
- [ ] Testing is appropriate and complete, if applicable
- [ ] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable

2024-05-24 20:23 UTC, dborman-hpe commented on ansible/config_sbps_iscsi_targets.yml
> +    - role: csm.sbps.apply_lable
spelling: `label`, not `lable`.

2024-05-29 16:33 UTC, mharding-hpe commented on CHANGELOG.md
> +## [1.19.1] - 2024-05-21
We should bump the minor version number for this, I think

```suggestion
## [1.20.0] - 2024-05-21
```

2024-05-29 16:34 UTC, mharding-hpe commented on CHANGELOG.md
> +[1.19.1]: https://github.com/Cray-HPE/csm-config/compare/1.19.0...1.19.1
```suggestion
[Unreleased]: https://github.com/Cray-HPE/csm-config/compare/1.20.0...HEAD

[1.19.1]: https://github.com/Cray-HPE/csm-config/compare/1.19.0...1.20.0
```

2024-06-04 14:08 UTC, mharding-hpe commented on CHANGELOG.md
> +## [1.20.1] - 2024-06-03
```suggestion
## [1.21.0] - 2024-06-03
```

2024-06-04 14:12 UTC, mharding-hpe commented on ansible/roles/csm.sbps.enable_sbps_marshal/README.md
Is there a reason you are doing this with a shell script instead of using [the builtin `systemd_service` Ansible module](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/systemd_service_module.html)?

2024-06-04 14:14 UTC, mharding-hpe requested changes

2024-06-04 14:14 UTC, mharding-hpe commented on ansible/roles/csm.sbps.enable_sbps_marshal/files/enable_sbps_marshal.sh
Is there a reason you are doing this with a shell script instead of using [the builtin `systemd_service` Ansible module](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/systemd_service_module.html)?

2024-06-11 19:25 UTC, dborman-hpe approved these changes
LGTM

2024-06-12 17:29 UTC, mharding-hpe approved these changes

2024-06-12 17:30 UTC, merged